services:
  nginx:
    build: .
    container_name: nginx
    restart: always
    ports:
      - "8443:443"
    # volumes:
    #   - wp-volume:/var/www/html

# volumes:
#   wp-volume:
#     driver_opts:
#       type: none
#       o: bind
#       device: ${HOME}/Documents/Transcendence/wp