services:
  auth_service:
    container_name: authentication
    restart: always
    build: ./backend/authentication
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 8081:8080
    volumes:
      - auth_data:/app/data
    networks:
      - internal
    environment:
      - NODE_ENV=development
    env_file:
      - .env

  user_service:
    container_name: user_management
    restart: always
    build: ./backend/userManagement
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 8082:8080
    volumes:
      - user_data:/app/data
    networks:
      - internal
    env_file:
      - .env

  nginx_service:
    container_name: nginx
    restart: always
    build: ./frontend
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost/index.html"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 8443:443

networks:
  internal:
    driver: bridge

volumes:
  auth_data:
    driver: local
    driver_opts:
      type: none
      device: ./backend/authentication/data
      o: bind
  user_data:
    driver: local
    driver_opts:
      type: none
      device: ./backend/userManagement/data
      o: bind
