services:
  nginx:
    container_name: transcendence_nginx
    restart: always
    build:
      context: frontend
    ports:
      - "8080:80"
    networks:
      - internal
    depends_on:
      - authentication
  authentication:
    container_name: transcendence_authentication
    restart: always
    build:
      context: services/authentication
    environment:
      - JWT_SECRET="Some secret"
    volumes:
      - auth_data:/var/authentication
    networks:
      - internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://authentication/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      - routing
  routing:
    container_name: transcendence_routing
    restart: always
    build:
      context: services/routing
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://routing/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      - matchmaking
      - game
  matchmaking:
    container_name: transcendence_matchmaking
    restart: always
    build:
      context: services/matchmaking
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://matchmaking/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      - game
  game:
    container_name: transcendence_game
    restart: always
    build:
      context: services/game
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://game/health" ]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  internal:

volumes:
  auth_data:
